version: '2'
services:
  web:
    build: .
    ports:
      - "3030:3030"
    volumes:
      - .:/code
    depends_on:
      # - index
      # - queue
      - database
  # index:
    # image: elasticsearch
  # queue:
    # image: rabbitmq
  database:
    image: mongo
